### PR TITLE
Implement SplitCycle algorithm as Python package

### PR DESCRIPTION
**Pull request by quantum9Innovation**
@wesholliday After reading the SplitCycle paper and reviewing the current code samples, I wanted to combine existing implementations into a package that makes the algorithm accessible to the Python community.

This PR adds a Python package that makes it easy to use an efficient version of the SplitCycle voting algorithm. I'm aware that an implementation of this algorithm is already defined in the `pref_voting` package, but this implementation is intended primarily for voting theorists and others interested in comparing different voting methods, whereas the SplitCycle Python package is intended for general purpose use (e.g. to quickly determine the SplitCycle winner from a set of ballots or to power online voting systems).

The primary benefit of this new package is that it prioritizes efficiency and speed, using a dead-simple implementation of the SplitCycle algorithm and ballot parser to maximize ease-of-use. Unlike `pref_voting`, which requires the installation of numerous external dependencies including `numba` and its peer dependency `llvmlite` (which doesn't compile correctly on some platforms), the SplitCycle package I've implemented uses only `numpy` (for basic 2D array processing) and `tabulate` for pretty-printing voting margin graphs.

I've created relevant manifest files (both for Poetry, the recommended way to install the package locally, and for `pip`) and automated workflows to support the package (one for linting and another for deploying the package to PyPI, though this requires setting `PYPI_API_TOKEN` in repository secrets). Running `poetry install` from the root directory will install the package in a local virtual environment for testing purposes.

The package contains two main exported functions, `splitcycle.elect` and `splitcycle.splitcycle`. `splitcycle.splitcycle` picks the SplitCycle winners from a voting margins graph, and also features automatic type checking to ensure that the matrix passed in as a voting margins graph has all of the requisite properties to be used as a margins graph (i.e. reverse diagonal symmetry and zero diagonal entries). `splitcycle.elect` will automatically generate the voting margins graph from a set of ballots and then return the SplitCycle winners, offering even greater ease-of-use with real data. The package also contains various utilities that can be used to preprocess ballots and other data before they are passed into `splitcycle.elect`.

The main SplitCycle implementation at `splitcycle.splitcycle` is very similar to algorithm's implementation in `pref_voting`, except that it uses breadth-first search instead of depth-first search when searching for strong paths in the margins graph. This is a small performance improvement that will result in faster detection of strong paths when they exist, since most Condorcet cycles are relatively shallow. In the more likely case that no strong path exists between two candidates in the margins graph, this change is irrelevant as the entire graph must still be traversed before it can be determined that no strong path exists. 

Lastly, I've made some simple repository changes, like deleting `DS_Store` file remnants. Documentation for all methods in the SplitCycle package is available inline and can be accessed by users through the built-in `help` command from a REPL or other Python environment. I haven't updated the README or created any external documentation, so I'll leave it to you to decide how you want to display the documentation (e.g. on a separate Markdown page, with pdoc, etc.). In a later PR, I will likely further improve the efficiency of the current SplitCycle implementation to use multithreading with large numbers of candidates and to include tests (probably using `pytest`) and code coverage analysis.

If you want to experiment with the code, here are some tests to get started:

```py
import splitcycle
candidates = ['A', 'B', 'C', 'D', 'E']
ballots = splitcycle.utils.gen_random_ballots(20, 5)
splitcycle.utils.info(ballots, candidates)
winners = splitcycle.elect(ballots, candidates)
print(winners)
```

### CODE REVIEW

**Comment by wesholliday** [comment]
Thanks, @quantum9Innovation, this is very interesting (and sorry for the delayed reply)! Just a question about this: "it uses breadth-first search instead of depth-first search when searching for strong paths in the margins graph. This is a small performance improvement that will result in faster detection of strong paths when they exist, since most Condorcet cycles are relatively shallow." Do you have some examples showing this performance improvement? We seem to find that the depth-first search is faster on (1) margin graphs generated using the (admittedly unrealistic) impartial culture model (using generate_profile in pref_voting), (2) margin graphs generated using the (also highly unrealistic) random edge-ordered tournament model (using generate_edge_ordered_tournament in pref_voting), and (3) margin graphs from real elections held on StableVoting.org.

**Comment by quantum9Innovation** [comment]
Those are some interesting observations. I didn't perform any tests directly comparing the runtime of the algorithm with depth-first search vs breadth-first search, but this is definitely something I'll look into now that you mention it. [Tideman's research](https://www.researchgate.net/publication/226683580_Modeling_the_Outcomes_of_Vote-Casting_in_Actual_Elections) suggests that the spatial voting model is the most accurate at representing real world election data, so I will add some tests with these models in spaces of various dimensions and compare algorithm performance using depth-first search.

**Comment by wesholliday** [comment]
I just tried various spatial models we have in pref_voting (see https://pref-voting.readthedocs.io/en/latest/generate_profiles.html) and the DFS version still seems to be faster than the BFS version.

**Comment by quantum9Innovation** [comment]
I'm currently working on some new performance improvements. I've also looked into the runtime with DFS vs BFS and confirmed DFS is faster in most cases (I'm currently looking into a few special cases and further opportunities for optimization). I'll let you know when I'm done with these changes and testing (likely in a few weeks).

**Pull request merged**
